name: decrypt-on-github
on:
  push:
  workflow_dispatch:

jobs:
  decrypt-by-sops:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show encrypted files
        run:  find config -name '*.encrypted.json' | xargs -I{} sh -c 'ls -lh {}; cat {}'

      - name: Setup SOPS
        uses: nhedger/setup-sops@v2
        with:
          version: "latest"
          token: ${{ github.token }}

      - name: Check sops version
        run: sops --version

      - name: Decrypt - Prod
        env:
          SOPS_AGE_KEY: ${{ secrets.AGE_KEY_01_PROD }}
        run: |
          sops --decrypt --output=config/service_a/prod/main.yaml config/service_a/prod/main.encrypted.yaml
          sops --decrypt --output=config/service_a/prod/main.json config/service_a/prod/main.encrypted.json

      - name: Decrypt - Stg
        env:
          SOPS_AGE_KEY: ${{ secrets.AGE_KEY_01_STG }}
        run: |
          sops --decrypt --output=config/service_a/stg/main.yaml config/service_a/stg/main.encrypted.yaml
          sops --decrypt --output=config/service_a/stg/main.json config/service_a/stg/main.encrypted.json

      - name: Show decrypted files
        run:  find config -name '*.json' -not -path '*encrypted*' | xargs -I{} sh -c 'ls -lh {}; cat {}'

